# Generated by Django 5.0.7 on 2026-01-15 00:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lobby',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Lobby', max_length=64)),
                ('status', models.CharField(choices=[('WAITING', 'Waiting'), ('RUNNING', 'Running'), ('FINISHED', 'Finished')], default='WAITING', max_length=16)),
                ('day', models.PositiveIntegerField(default=0)),
                ('max_days', models.PositiveIntegerField(default=30)),
                ('map_w', models.PositiveIntegerField(default=900)),
                ('map_h', models.PositiveIntegerField(default=560)),
                ('food_per_day', models.PositiveIntegerField(default=50)),
                ('phase', models.CharField(choices=[('DAY', 'Day'), ('PAUSE', 'Pause')], default='DAY', max_length=8)),
                ('phase_started_at', models.DateTimeField(blank=True, null=True)),
                ('phase_end_at', models.DateTimeField(blank=True, null=True)),
                ('current_payload_day', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('active', models.BooleanField(default=True)),
                ('lobby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foods', to='game.lobby')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_index', models.PositiveIntegerField()),
                ('session_key', models.CharField(blank=True, max_length=64, null=True)),
                ('display_name', models.CharField(default='Player', max_length=32)),
                ('is_bot', models.BooleanField(default=False)),
                ('color_hex', models.CharField(default='#999999', max_length=16)),
                ('coins', models.IntegerField(default=0)),
                ('energy_bonus', models.IntegerField(default=0)),
                ('vision_bonus', models.IntegerField(default=0)),
                ('base_x', models.FloatField(default=80)),
                ('base_y', models.FloatField(default=80)),
                ('lobby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='game.lobby')),
            ],
            options={
                'unique_together': {('lobby', 'slot_index')},
            },
        ),
        migrations.CreateModel(
            name='Creature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alive', models.BooleanField(default=True)),
                ('size', models.FloatField(default=1.0)),
                ('speed', models.FloatField(default=1.0)),
                ('danger', models.FloatField(default=0.5)),
                ('energy_max', models.FloatField(default=100.0)),
                ('energy', models.FloatField(default=100.0)),
                ('vision', models.FloatField(default=90.0)),
                ('x', models.FloatField(default=100.0)),
                ('y', models.FloatField(default=100.0)),
                ('carried_food', models.IntegerField(default=0)),
                ('created_day', models.IntegerField(default=0)),
                ('lobby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creatures', to='game.lobby')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creatures', to='game.playerslot')),
            ],
        ),
        migrations.CreateModel(
            name='DayLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.PositiveIntegerField()),
                ('payload', models.JSONField(default=dict)),
                ('lobby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='day_logs', to='game.lobby')),
            ],
            options={
                'unique_together': {('lobby', 'day')},
            },
        ),
    ]
